server:
  port: 10080
  servlet:
    context-path: /pc-club
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://124.221.116.183:8898/Jinyan
    username: root
    password: 
# mysqlPlus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  global-config:
    banner: false
# mysql日志级别
logging:
  level:
    root: INFO
    com.pcstudio.blossom.mapper: debug
